<a href="https://colab.research.google.com/github/JaySanthanam/Programming-for-data/blob/main/Projects/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [4]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

url_new = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/LGBF_Data_Table_May2023.csv"
new_df = get_data(url_new)
url_old = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/LGBF_Data_Table_Mar2023.csv"
old_df = get_data(url_old)

In [167]:
old_df.dtypes

Indicator_Code     object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [168]:
new_df.dtypes

Indicator_Code     object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [ ]:
#new_df['Indicator'] = new_df['Indicator'].map("{:.4f}".format)
#new_df['Numerator'] = new_df['Numerator'].map('{:.4f}'.format)
#new_df['Denominator'] = new_df['Denominator'].map('{:.4f}'.format)

In [ ]:
#old_df['Indicator'] = old_df['Indicator'].map('{:.4f}'.format)
#old_df['Numerator'] = old_df['Numerator'].map('{:.4f}'.format)
#old_df['Denominator'] = old_df['Denominator'].map('{:.4f}'.format)

In [5]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [170]:
old_df.head()

  Indicator_Code LocalAuthority     Year  Indicator  Numerator  Denominator
0          C&L01  Aberdeen City  2010-11     0.4067   785.0188    1922292.0
1          C&L01  Aberdeen City  2011-12     0.9225  1886.6034    2045051.0
2          C&L01  Aberdeen City  2012-13     4.3355  9381.0432    2163756.0
3          C&L01  Aberdeen City  2013-14     4.0441  8988.3238    2222588.0
4          C&L01  Aberdeen City  2014-15     3.4761  8645.5731    2487138.0

In [171]:
new_df.head()

  Indicator_Code LocalAuthority     Year  Indicator  Numerator  Denominator
0          C&L01  Aberdeen City  2010-11     0.4067   785.0188    1922292.0
1          C&L01  Aberdeen City  2011-12     0.9225  1886.6034    2045051.0
2          C&L01  Aberdeen City  2012-13     4.3355  9381.0432    2163756.0
3          C&L01  Aberdeen City  2013-14     4.0441  8988.3238    2222588.0
4          C&L01  Aberdeen City  2014-15     3.4761  8645.5731    2487138.0

In [172]:
old_df.reset_index(drop=True).equals(new_df.reset_index(drop=True))

False

In [6]:
df1 = old_df
df2 =new_df

In [11]:
out = pd.merge(df1, df2, on=['Indicator_Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_df1', '_df2')).set_index(['Indicator_Code', 'LocalAuthority','Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)) \
                           .swaplevel()

out = out['df1'].compare(out['df2'])

In [12]:
out

                                        Indicator          Numerator  \
                                             self   other       self
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22    6.2791  6.2985  3551.1012
               Clackmannanshire 2021-22    5.2879  4.8465   610.5016
               East Ayrshire    2010-11    2.5983  2.6003        NaN
C&L02          Renfrewshire     2021-22    1.5500  1.5458        NaN
C&L03          Edinburgh City   2014-15    1.6885  2.3500        NaN
...                                           ...     ...        ...
CHN23          Scotland         2021-22       NaN  0.1586        NaN
                                2021-22       NaN  0.1586        NaN
                                2021-22       NaN  0.1586        NaN
                                2021-22       NaN  0.1586        NaN
                                2021-22       NaN  0.1586        NaN

                                                   Denominator
                                             other        self other
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22  3562.0923         NaN   NaN
               Clackmannanshire 2021-22   559.5432         NaN   NaN
               East Ayrshire    2010-11        NaN         NaN   NaN
C&L02          Renfrewshire     2021-22        NaN         NaN   NaN
C&L03          Edinburgh City   2014-15        NaN         NaN   NaN
...                                            ...         ...   ...
CHN23          Scotland         2021-22        NaN         NaN   NaN
                                2021-22        NaN         NaN   NaN
                                2021-22        NaN         NaN   NaN
                                2021-22        NaN         NaN   NaN
                                2021-22        NaN         NaN   NaN

[5605 rows x 6 columns]

In [173]:
diff = old_df.compare(new_df, keep_equal=True, keep_shape = True)

ValueError: ignored

#Identify the size difference between the two dataframes.

In [114]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [115]:
df1 = old_df
df2 = new_df

out_diff = dataframe_difference(df1, df2)
out_diff

,Indicator_Code,LocalAuthority,Year,Indicator,Numerator,Denominator,_merge
35,C&L01,Angus,2021-22,6.2791,3.551101e+03,565544.0,left_only
59,C&L01,Clackmannanshire,2021-22,5.2879,6.105016e+02,115452.0,left_only
84,C&L01,East Ayrshire,2010-11,2.5983,3.094478e+03,1190983.0,left_only
683,C&L02,Renfrewshire,2021-22,1.5500,3.170412e+03,2051020.0,left_only
884,C&L03,Edinburgh City,2014-15,1.6885,2.937448e+03,1250000.0,left_only
...,...,...,...,...,...,...,...
64400,SW05,Scotland,2021-22,734.8025,1.067870e+06,27947.5,right_only
64401,SW05,Scotland,2021-22,734.8025,1.067870e+06,27947.5,right_only
64402,SW05,Scotland,2021-22,734.8025,1.067870e+06,27947.5,right_only
64403,SW05,Scotland,2021-22,734.8025,1.067870e+06,27947.5,right_only
64404,SW05,Scotland,2021-22,734.8025,1.067870e+06,27947.5,right_only

In [116]:
old_df

,Indicator_Code,LocalAuthority,Year,Indicator,Numerator,Denominator
0,C&L01,Aberdeen City,2010-11,0.4067,785.0188,1922292.0
1,C&L01,Aberdeen City,2011-12,0.9225,1886.6034,2045051.0
2,C&L01,Aberdeen City,2012-13,4.3355,9381.0432,2163756.0
3,C&L01,Aberdeen City,2013-14,4.0441,8988.3238,2222588.0
4,C&L01,Aberdeen City,2014-15,3.4761,8645.5731,2487138.0
...,...,...,...,...,...,...
33663,SW08,Scotland,2017-18,761.7435,341239.0000,447971.0
33664,SW08,Scotland,2018-19,792.6600,360451.0000,454736.0
33665,SW08,Scotland,2019-20,773.7831,360463.0000,465845.0
33666,SW08,Scotland,2020-21,484.2822,227524.0000,469817.0
33667,SW08,Scotland,2021-22,747.9233,357719.0000,478283.0

In [117]:
new_df

,Indicator_Code,LocalAuthority,Year,Indicator,Numerator,Denominator
0,C&L01,Aberdeen City,2010-11,0.4067,785.0188,1922292.0
1,C&L01,Aberdeen City,2011-12,0.9225,1886.6034,2045051.0
2,C&L01,Aberdeen City,2012-13,4.3355,9381.0432,2163756.0
3,C&L01,Aberdeen City,2013-14,4.0441,8988.3238,2222588.0
4,C&L01,Aberdeen City,2014-15,3.4761,8645.5731,2487138.0
...,...,...,...,...,...,...
60773,SW07,Scotland,2017-18,0.8538,NaN,NaN
60774,SW07,Scotland,2018-19,0.8217,NaN,NaN
60775,SW07,Scotland,2019-20,0.8180,NaN,NaN
60776,SW07,Scotland,2020-21,0.8250,NaN,NaN
60777,SW07,Scotland,2021-22,0.7580,NaN,NaN

In [119]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)


df1 = old_df.set_index(['Indicator_Code', 'LocalAuthority','Year'])
df2 = new_df.set_index(['Indicator_Code', 'LocalAuthority','Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                                         Indicator_old  Numerator_old  \
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22         6.2791      3551.1012
               Clackmannanshire 2021-22         5.2879       610.5016
               East Ayrshire    2010-11         2.5983      3094.4776
               Scotland         2019-20         2.8858    150191.5886
                                2019-20         2.8858    150191.5886
...                                                ...            ...
SW07           West Lothian     2017-18         0.8707            NaN
                                2018-19         0.8542            NaN
                                2019-20         0.8125            NaN
                                2020-21         0.8430            NaN
                                2021-22         0.8075            NaN

                                         Denominator_old  Indicator_new  \
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22         565544.0         6.2985
               Clackmannanshire 2021-22         115452.0         4.8465
               East Ayrshire    2010-11        1190983.0         2.6003
               Scotland         2019-20       52045545.0         2.8610
                                2019-20       52045545.0         2.8610
...                                                  ...            ...
SW07           West Lothian     2017-18              NaN         0.8707
                                2018-19              NaN         0.8542
                                2019-20              NaN         0.8125
                                2020-21              NaN         0.8430
                                2021-22              NaN         0.8075

                                         Numerator_new  Denominator_new  \
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22      3562.0923         565544.0
               Clackmannanshire 2021-22       559.5432         115452.0
               East Ayrshire    2010-11      3094.4776        1190983.0
               Scotland         2019-20    148902.3909       52045545.0
                                2019-20    148902.3909       52045545.0
...                                                ...              ...
SW07           West Lothian     2017-18            NaN              NaN
                                2018-19            NaN              NaN
                                2019-20            NaN              NaN
                                2020-21            NaN              NaN
                                2021-22            NaN              NaN

                                         Indicator_diff  Numerator_diff  \
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22            True            True
               Clackmannanshire 2021-22            True            True
               East Ayrshire    2010-11            True           False
               Scotland         2019-20            True            True
                                2019-20            True            True
...                                                 ...             ...
SW07           West Lothian     2017-18           False            True
                                2018-19           False            True
                                2019-20           False            True
                                2020-21           False            True
                                2021-22           False            True

                                         Denominator_diff  Record_Changed  \
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22             False            True
               Clackmannanshire 2021-22             False            True
               East Ayrshire    2010-11             False            True
               Scotland         2019-20             False            True
                                2019-20             False            True
...                                                   ...             ...
SW07           West Lothian     2017-18              True            True
                                2018-19              True            True
                                2019-20              True            True
                                2020-21              True            True
                                2021-22              True            True

                                                   Cols_Changed
Indicator_Code LocalAuthority   Year
C&L01          Angus            2021-22    Indicator, Numerator
               Clackmannanshire 2021-22    Indicator, Numerator
               East Ayrshire    2010-11               Indicator
               Scotland         2019-20    Indicator, Numerator
                                2019-20    Indicator, Numerator
...                                                         ...
SW07           West Lothian     2017-18  Numerator, Denominator
                                2018-19  Numerator, Denominator
                                2019-20  Numerator, Denominator
                                2020-21  Numerator, Denominator
                                2021-22  Numerator, Denominator

[35595 rows x 11 columns]

#Actual code starts here

##1. first find new year's data that is added for this year

In [120]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Indicator_Code','Year_new'], right_on=['LocalAuthority','Indicator_Code','Year'])
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([ 5006,  5018,  5030,  5042,  5054,  5066,  5078,  5090,  5102,
        5114,  5126,  5138,  5150,  5162,  5174,  5186,  5198,  5210,
        5222,  5234,  5246,  5258,  5270,  5282,  5294,  5306,  5318,
        5330,  5342,  5354,  5366,  5378,  5390,  5402,  5414,  5426,
        5438,  5450,  5462,  5474,  5486,  5498,  5510,  5522,  5534,
        5546,  5558,  5570,  5582,  5594,  5606,  5618,  5630,  5642,
        5654,  5666,  5678,  5690,  5702,  5714,  5726,  5738,  5750,
        5762,  5774,  5786,  5798,  5810,  5822,  5834,  5846,  5858,
        5870,  5882,  5894,  5906,  5918,  5930,  5942,  5954,  5966,
        5978,  5990,  6002,  6014,  6026,  6038,  6050,  6062,  6074,
        6086,  6098,  6110,  6122,  6134,  6146,  9184,  9193,  9202,
        9211,  9220,  9229,  9238,  9247,  9256,  9265,  9274,  9283,
        9292,  9301,  9310,  9319,  9328,  9337,  9346,  9355,  9364,
        9373,  9382,  9391,  9400,  9409,  9418,  9427,  9436,  9445,
        9454,  9463, 10830, 10840, 10850, 10860, 10870, 10880, 10890,
       10900, 10910, 10920, 10930, 10940, 10950, 10960, 10970, 10980,
       10990, 11000, 11010, 11020, 11030, 11040, 11050, 11060, 11070,
       11080, 11090, 11100, 11110, 11120, 11130, 11140, 11152, 11164,
       11176, 11188, 11200, 11212, 11224, 11236, 11248, 11260, 11272,
       11284, 11296, 11308, 11320, 11332, 11344, 11356, 11368, 11380,
       11392, 11404, 11416, 11428, 11440, 11452, 11464, 11476, 11488,
       11500, 11512, 11524, 35395, 35407, 35419, 35431, 35443, 35455,
       35467, 35479, 35491, 35503, 35515, 35527, 35539, 35551, 35563,
       35575, 35587, 35599, 35611, 35623, 35635, 35647, 35659, 35671,
       35683, 35695, 35707, 35719, 35731, 35743, 35755, 35767, 35779,
       35791, 35803, 35815, 35827, 35839, 35851, 35863, 35875, 35887,
       35899, 35911, 35923, 35935, 35947, 35959, 35971, 35983, 35995,
       36007, 36019, 36031, 36043, 36055, 36067, 36079, 36091, 36103,
       36115, 36127, 36139, 36151, 36163, 36175, 36187, 36199, 36211,
       36223, 36235, 36247, 36259, 36271, 36283, 36295, 36307, 36319,
       36331, 36343, 36355, 36367, 36379, 36391, 36403, 36415, 36427,
       36439, 36451, 36463, 36475, 36487, 36499, 36511, 36523, 36535,
       39573, 39582, 39591, 39600, 39609, 39618, 39627, 39636, 39645,
       39654, 39663, 39672, 39681, 39690, 39699, 39708, 39717, 39726,
       39735, 39744, 39753, 39762, 39771, 39780, 39789, 39798, 39807,
       39816, 39825, 39834, 39843, 39852, 41219, 41229, 41239, 41249,
       41259, 41269, 41279, 41289, 41299, 41309, 41319, 41329, 41339,
       41349, 41359, 41369, 41379, 41389, 41399, 41409, 41419, 41429,
       41439, 41449, 41459, 41469, 41479, 41489, 41499, 41509, 41519,
       41529, 41541, 41553, 41565, 41577, 41589, 41601, 41613, 41625,
       41637, 41649, 41661, 41673, 41685, 41697, 41709, 41721, 41733,
       41745, 41757, 41769, 41781, 41793, 41805, 41817, 41829, 41841,
       41853, 41865, 41877, 41889, 41901, 41913])

# create a new data frame with just the new year's data

In [121]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Indicator_Code", "LocalAuthority", 'Year'], keep=False)

In [122]:
new_Data

,Indicator_Code,LocalAuthority,Year,Indicator,Numerator,Denominator
15171,CORP09,Aberdeen City,2018-19 Q1,0.980,2340.0,3035.0
15172,CORP09,Aberdeen City,2018-19 Q2,0.990,2130.0,2800.0
15173,CORP09,Aberdeen City,2018-19 Q3,0.980,1925.0,2645.0
15174,CORP09,Aberdeen City,2018-19 Q4,0.980,2335.0,3460.0
15175,CORP09,Aberdeen City,2019-20 Q1,0.980,2145.0,3245.0
...,...,...,...,...,...,...
11476,CHN23,South Ayrshire,2021-22,0.176,NaN,NaN
11488,CHN23,South Lanarkshire,2021-22,0.156,NaN,NaN
11500,CHN23,Stirling,2021-22,0.143,NaN,NaN
11512,CHN23,West Dunbartonshire,2021-22,0.117,NaN,NaN
11524,CHN23,West Lothian,2021-22,0.198,NaN,NaN

In [123]:
#new year added data
new_Data = new_df.loc[new_year_df]
new_Data = new_Data.rename(columns={"Indicator": "New_Indicator", "Numerator": "New_Numerator", "Denominator": "New_Denominator"})
new_Data = new_Data.drop_duplicates()
new_Data

,Indicator_Code,LocalAuthority,Year,New_Indicator,New_Numerator,New_Denominator
5006,CHN08a,Aberdeen City,2021-22,4154.9845,NaN,NaN
5018,CHN08a,Aberdeenshire,2021-22,2579.0232,NaN,NaN
5030,CHN08a,Angus,2021-22,3505.4415,NaN,NaN
5042,CHN08a,Argyll & Bute,2021-22,2931.0285,NaN,NaN
5054,CHN08a,Clackmannanshire,2021-22,4729.8493,NaN,NaN
...,...,...,...,...,...,...
35779,CHN08b,Scotland,2021-22,402.2039,236586.8746,11312.0
36163,CHN09,Scotland,2021-22,0.8981,NaN,NaN
39573,CHN17,Scotland,2021-22,0.8214,NaN,NaN
41219,CHN22,Scotland,2021-22,0.0801,NaN,NaN
41541,CHN23,Scotland,2021-22,0.1586,NaN,NaN

In [ ]:
from google.colab import files
new_Data. to_excel('newyear_Data.xlsx')
files.download('newyear_Data.xlsx')

# Create a dataframe with just changes/updates to old data

In [127]:
#make df with only changes
new_update= new_df.drop(new_df.index[new_year_df], inplace=False).reset_index(drop=True)
new_update

,Indicator_Code,LocalAuthority,Year,Indicator,Numerator,Denominator
0,C&L01,Aberdeen City,2010-11,0.4067,785.0188,1922292.0
1,C&L01,Aberdeen City,2011-12,0.9225,1886.6034,2045051.0
2,C&L01,Aberdeen City,2012-13,4.3355,9381.0432,2163756.0
3,C&L01,Aberdeen City,2013-14,4.0441,8988.3238,2222588.0
4,C&L01,Aberdeen City,2014-15,3.4761,8645.5731,2487138.0
...,...,...,...,...,...,...
60005,SW07,Scotland,2017-18,0.8538,NaN,NaN
60006,SW07,Scotland,2018-19,0.8217,NaN,NaN
60007,SW07,Scotland,2019-20,0.8180,NaN,NaN
60008,SW07,Scotland,2020-21,0.8250,NaN,NaN
60009,SW07,Scotland,2021-22,0.7580,NaN,NaN

In [128]:
np.array_equal(old_df,new_df)

False

In [129]:
old_df.values==new_update.values

<ipython-input-129-e2be420cbd72>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  old_df.values==new_update.values

False

In [95]:
#compare the old df to find the changes
comparison_values = old_df.values == new_update.values
rows,cols=np.where(comparison_values==False)
rows

<ipython-input-95-6d539fd913ec>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  comparison_values = old_df.values == new_update.values

ValueError: ignored

#Add new columns with the changes (keeping the old values)

In [ ]:
change_df = pd.DataFrame()
change_df = old_df.loc[rows]
AddNew_df = new_update.loc[rows]
change_df.insert(loc = 4, column = "New_Indicator", value = AddNew_df["Indicator"].values)
change_df.insert(loc = 6, column = "New_Numerator", value = AddNew_df["Numerator"].values)
change_df.insert(loc = 8, column ="New_Denominator", value = AddNew_df["Denominator"].values)
change_df = change_df.drop_duplicates()
change_df

,Code,LocalAuthority,Year,Indicator,New_Indicator,Numerator,New_Numerator,Denominator,New_Denominator
35,C&L01,Angus,2021-22,6.2791,6.2985,3551.1012,3562.0923,565544.0,565544.0
59,C&L01,Clackmannanshire,2021-22,5.2879,4.8465,610.5016,559.5432,115452.0,115452.0
84,C&L01,East Ayrshire,2010-11,2.5983,2.6003,3094.4776,3094.4776,1190983.0,1190983.0
300,C&L01,Scotland,2010-11,4.3749,3.8943,198956.0517,2859.0952,45459818.0,734048.0
301,C&L01,Scotland,2011-12,3.9170,3.1828,188806.0265,2587.0990,48202343.0,812833.0
...,...,...,...,...,...,...,...,...,...
31155,SW07,West Lothian,2017-18,0.8707,0.8538,NaN,NaN,NaN,NaN
31156,SW07,West Lothian,2018-19,0.8542,0.8217,NaN,NaN,NaN,NaN
31157,SW07,West Lothian,2019-20,0.8125,0.8180,NaN,NaN,NaN,NaN
31158,SW07,West Lothian,2020-21,0.8430,0.8250,NaN,NaN,NaN,NaN
31159,SW07,West Lothian,2021-22,0.8075,0.7580,NaN,NaN,NaN,NaN

In [ ]:
from google.colab import files
change_df. to_excel('Data_changes.xlsx')
files.download('Data_changes.xlsx')

#Add the new year's data in the end in the new value columns

In [ ]:
#Add all changes including new data for the new year

All_changes = pd.concat([change_df, new_Data],  join="outer", axis=0).reset_index()
#All_changes = pd.concat([new_Data, change_df], ignore_index=True)
All_changes = All_changes.sort_values(by=['Year','LocalAuthority'], ascending=[False, True])
All_changes

,index,Code,LocalAuthority,Year,Indicator,New_Indicator,Numerator,New_Numerator,Denominator,New_Denominator
110,407,C&L02,Aberdeen City,2021-22,2.4476,2.1544,3297.3084,3192.3941,1347180.0,1481816.0
506,803,C&L03,Aberdeen City,2021-22,3.1229,47.2555,3718.9642,415.6607,1190854.0,8796.0
865,1162,C&L04,Aberdeen City,2021-22,14269.6162,21752.0543,3245.0000,1875.0,227430.0,86220.0
2317,2614,CHN01,Aberdeen City,2021-22,5902.8563,5711.4908,83136.1361,52134.0,14084.0,9128.0
2713,3010,CHN02,Aberdeen City,2021-22,7107.2086,7866.6148,71363.7459,59298.0,10041.0,7538.0
...,...,...,...,...,...,...,...,...,...,...
23235,23532,ENV04e,South Ayrshire,2007-11,0.4461,4372.3525,NaN,1374.49,NaN,314360.0
23247,23544,ENV04e,South Lanarkshire,2007-11,0.3873,10411.2838,NaN,953.4628,NaN,91580.0
23259,23556,ENV04e,Stirling,2007-11,0.4834,3608.1957,NaN,324.2318,NaN,89860.0
23271,23568,ENV04e,West Dunbartonshire,2007-11,0.3585,11269.645,NaN,2052.6478,NaN,182140.0
23283,23580,ENV04e,West Lothian,2007-11,0.2853,15435.0184,NaN,3535.563,NaN,229060.0

In [ ]:
from google.colab import files
change_df. to_excel('All_changes.xlsx')
files.download('All_changes.xlsx')

#Highlight changes in the new value columns

In [ ]:
def set_colormap(x):
    c = f'background-color: yellow'
    # DataFrame of styles
    df1 = pd.DataFrame('', index=x.index, columns=x.columns)
    #set new columns by condition
    columns = len(x.columns)
    for i in range (4,columns-1,2):
        col1 = x.columns[i]
        col2 = x.columns[i+1]
        m = x[col1]!=x[col2]
        # set columns by condition
        df1.loc[m, col2] = c
    return df1

All_changes = All_changes.style.apply(set_colormap, axis=None)

#Write to CSV.

In [ ]:
from google.colab import files
All_changes. to_excel('Final_changes.xlsx')
files.download('Final_changes.xlsx')

#Stops here!!!!!!!!!!!!!!!!