<a href="https://colab.research.google.com/github/JaySanthanam/Programming-for-data/blob/main/Copy_of_Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

In [ ]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

url_new = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/test_new.csv"
new_df = get_data(url_new)
url_old = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/test_old1.csv"
url_diff = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/test_old.csv"
old_df = get_data(url_old)
diff_df = get_data(url_diff)

In [ ]:
old_df.shape[0]

384

In [ ]:
old_df.equals(new_df)

False

In [ ]:
comparison_values = old_df.values == new_df.values
print(comparison_values)

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True False  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]

In [ ]:
import numpy as np
rows,cols=np.where(comparison_values==False)

In [ ]:
out_df = get_data(url_old)

In [ ]:
for item in zip(rows,cols):
    if old_df.iloc[item] != new_df.iloc[item]:
       out_df.iloc[item[0], item[1]] = '{} --> {}'.format(old_df.iloc[item[0], item[1]],new_df.iloc[item[0], item[1]])

In [ ]:
out_df.shape[0]

384

In [ ]:
out_df = out_df.dropna(how='all', axis=0)
out_df

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,785.018799,1922292,4.374884,198956.0517,45459818 --> 45458000,4.285538,10653.67251,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,1886.603428,2045051,3.916959,188806.0265,48202343,4.175468725 --> 4.25,10198.31163,2355970.75,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,9381.043169,2163756,3.73456,192795.1341,51624697,4.353732,11272.60325,2601296.5 --> 2612960.5,Urban
3,C&L01,Aberdeen City,2013-14,4.044078,8988.323761,2222588,3.710667,197855.9712,53320837,4.355361,11913.65901,2660076.25,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,8645.573117 --> 8600.32,2487138,3.408087,179623.6567,52705262,4.064669,10315.28321,2672126.125,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,C&L01,West Lothian,2017-18,1.843244,4510.75788,2447198,2.98748,161301.3605,53992733,2.807878,4044.321994,1546902.375,3
380,C&L01,West Lothian,2018-19,2.39443,6097.571345,2546572,2.816481,153571.2585,54526069,2.46167,3848.31031,1594924.75,3
381,C&L01,West Lothian,2019-20,2.007365,5049.269872,2515378,2.885778,150191.5886,52045545,2.611569,3730.029529,1497042.25,3
382,C&L01,West Lothian,2020-21,22.000649,4619.323346,209962,41.36002281 --> 40.0,188666.6714,4561548,56.111328,4281.674517,119839.625,3
383,C&L01,West Lothian,2021-22,2.075107,2983.564522,1437783,6.433923,170577.7577,26512151,7.00436,3544.731442,708714.5,3

In [ ]:
import os  
os.makedirs('C:/Users/santhanam.jayanthi/Documents/Python_tests', exist_ok=True)  
out_df.to_csv('C:/Users/santhanam.jayanthi/Documents/Python_tests/out_df.csv')

In [ ]:
out_df.to_csv(os.getcwd()+'\\out_df.csv')

In [ ]:
out_df.to_csv('C:/Users/santhanam.jayanthi/Documents/Python_tests/out_df.csv',index=False, header=True)

In [ ]:
test_csv = pd.read_csv('C:/Users/santhanam.jayanthi/Documents/Python_tests/out_df.csv')
test_csv

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679401,785.0187987,1922292,4.374884466,198956.0517,45459818 --> 45458000,4.285538234,10653.67251,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524281,1886.603428,2045051,3.916959065,188806.0265,48202343,4.175468725 --> 4.25,10198.31163,2355970.75,Urban
2,C&L01,Aberdeen City,2012-13,4.335545113,9381.043169,2163756,3.734559758,192795.1341,51624697,4.353732323,11272.60325,2601296.5 --> 2612960.5,Urban
3,C&L01,Aberdeen City,2013-14,4.044078167,8988.323761,2222588,3.710667178,197855.9712,53320837,4.355360867,11913.65901,2660076.25,Urban
4,C&L01,Aberdeen City,2014-15,3.476122401,8645.573117 --> 8600.32,2487138,3.408087309,179623.6567,52705262,4.064668521,10315.28321,2672126.125,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,C&L01,West Lothian,2017-18,1.843243723,4510.75788,2447198,2.987480475,161301.3605,53992733,2.8078779,4044.321994,1546902.375,3
380,C&L01,West Lothian,2018-19,2.394429559,6097.571345,2546572,2.816481408,153571.2585,54526069,2.461669884,3848.31031,1594924.75,3
381,C&L01,West Lothian,2019-20,2.007364522,5049.269872,2515378,2.885778339,150191.5886,52045545,2.611569337,3730.029529,1497042.25,3
382,C&L01,West Lothian,2020-21,22.00064907,4619.323346,209962,41.36002281 --> 40.0,188666.6714,4561548,56.11132782,4281.674517,119839.625,3
383,C&L01,West Lothian,2021-22,2.075106943,2983.564522,1437783,6.433922572,170577.7577,26512151,7.004359576,3544.731442,708714.5,3

Let's try the index match

In [ ]:
test_df = pd.DataFrame()

In [ ]:
test_df = old_df.loc[rows]

In [ ]:
test1_df = new_df.loc[rows]

In [ ]:
test_df.insert(loc = 4, column = "New_LA_Indicator", value = test1_df["LA_IndicatorReal"].values)
test_df.insert(loc = 6, column = "New_LA_Numerator", value = test1_df["LA_Numerator_real"].values)
test_df.insert(loc = 8, column ="New_LA_Den", value = test1_df["LA_Den_Real"].values)
test_df.insert(loc = 10, column = "New_Scotland_Indicator", value = test1_df["Scotland_Indicator_Real"].values)
test_df.insert(loc = 12, column = "New_Scotland_Num", value = test1_df["Scotland_Num_Real"].values)
test_df.insert(loc = 14, column ="New_Scotland_Den", value = test1_df["Scotland_Den_Real"].values)
test_df.insert(loc = 16, column ="New_FG_Avg_Indicator", value = test1_df["FG_Avg_Indicator_Real"].values)
test_df.insert(loc = 18, column ="New_FG_Avg_Num", value = test1_df["FG_Avg_Num_Real"].values)
test_df.insert(loc = 20, column ="New_FG_Avg_Den", value = test1_df["FG_Avg_Den_Real"].values)

In [ ]:
test_df

,Code,LocalAuthority,Year,LA_IndicatorReal,New_LA_Indicator,LA_Numerator_real,New_LA_Numerator,LA_Den_Real,New_LA_Den,Scotland_Indicator_Real,...,New_Scotland_Num,Scotland_Den_Real,New_Scotland_Den,FG_Avg_Indicator_Real,New_FG_Avg_Indicator,FG_Avg_Num_Real,New_FG_Avg_Num,FG_Avg_Den_Real,New_FG_Avg_Den,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,0.406679,785.018799,785.018799,1922292,1922292,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,0.922524,1886.603428,1886.603428,2045051,2045051,3.916959,...,188806.0265,48202343,48202343,4.175469,4.250000,10198.311630,10198.311630,2355970.750,2355970.750,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,4.335545,9381.043169,9381.043169,2163756,2163756,3.734560,...,192795.1341,51624697,51624697,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2612960.500,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,3.476122,8645.573117,8600.320000,2487138,2487138,3.408087,...,179623.6567,52705262,52705262,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
6,C&L01,Aberdeen City,2016-17,3.764976,3.764976,9022.588442,9022.588442,2396458,2400458,3.244026,...,175314.3718,54042338,54042338,3.684838,3.684838,9674.825435,9674.825435,2702731.625,2702731.625,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
12,C&L01,Aberdeenshire,2010-11,5.520981,5.520981,6951.791277,6951.791277,1260286,1260286,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
24,C&L01,Angus,2010-11,2.415429,2.415429,3788.301079,3788.301079,1568948,1568948,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
26,C&L01,Angus,2012-13,2.121647,2.121647,2827.522335,2827.522335,1332704,1332704,3.734560,...,192795.1341,51624697,51624697,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
36,C&L01,Argyll & Bute,2010-11,2.982316,2.982316,1959.466075,1959.466075,656840,656840,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
46,C&L01,Argyll & Bute,2020-21,19.680022,19.680022,1513.775147,1513.775147,76919,80000,41.360023,...,188666.6714,4561548,4561548,23.984158,23.984158,3339.028773,3339.028773,144847.375,144847.375,Rural
48,C&L01,Clackmannanshire,2010-11,3.697085,3.697085,2019.852137,2019.852137,545939,545939,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
58,C&L01,Clackmannanshire,2020-21,17.830682,18.000000,790.241941,790.241941,44319,44319,41.360023,...,188666.6714,4561548,4561548,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3
60,C&L01,Dumfries & Galloway,2010-11,5.126625,5.126625,6636.304915,6636.304915,1293585,1293585,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
72,C&L01,Dundee City,2010-11,1.922484,1.922484,2801.173830,2801.173830,1460938,1460938,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
74,C&L01,Dundee City,2012-13,3.068683,3.068683,4492.380815,4492.380815,1463947,1463947,3.734560,...,192795.1341,51624697,52000000,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2601296.500,Urban
84,C&L01,East Ayrshire,2010-11,2.598255,2.598255,3094.477557,3094.477557,1190983,1190983,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
96,C&L01,East Dunbartonshire,2010-11,3.265759,3.265759,3227.573365,3227.573365,987719,987719,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
97,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884,3.916959,...,188806.0265,48202343,50000000,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
97,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884,3.916959,...,188806.0265,48202343,50000000,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
108,C&L01,East Lothian,2010-11,6.297369,6.297369,5831.568219,5831.568219,926802,926802,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
120,C&L01,East Renfrewshire,2010-11,6.186456,6.186456,4484.589338,4484.589338,724197,724197,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
121,C&L01,East Renfrewshire,2011-12,4.628932,4.628932,3333.727808,3333.727808,720196,720196,3.916959,...,200000.0000,48202343,48202343,3.337976,3.337976,4860.219433,4860.219433,1415648.375,1415648.375,3
132,C&L01,Edinburgh City,2010-11,2.945345,2.945345,11530.040630,11530.040630,3912923,3912923,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
136,C&L01,Edinburgh City,2014-15,2.905323,2.905323,10749.172060,10749.172060,3699830,3699830,3.408087,...,179623.6567,52705262,52705262,4.064669,4.000000,10315.283210,10315.283210,2672126.125,2672126.125,Urban
144,C&L01,Eilean Siar,2010-11,2.600283,2.600283,836.778280,836.778280,321497,321497,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
152,C&L01,Eilean Siar,2018-19,3.518330,4.000000,986.435251,986.435251,280371,280371,2.816481,...,153571.2585,54526069,54526069,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
156,C&L01,Falkirk,2010-11,6.100191,6.100191,5742.837680,5742.837680,941279,941279,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
168,C&L01,Fife,2010-11,4.658328,4.658328,11343.952970,11343.952970,2432587,2432587,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
180,C&L01,Glasgow City,2010-11,9.181096,9.181096,41859.864260,41859.864260,4558310,4558310,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
184,C&L01,Glasgow City,2014-15,5.312010,5.312010,31728.804790,31728.804790,5973048,5973048,3.408087,...,180000.0000,52705262,52705262,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
192,C&L01,Highland,2010-11,4.103765,4.103765,8961.784465,8961.784465,2185899,2185899,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
204,C&L01,Inverclyde,2010-11,1.774601,1.774601,1965.627918,1965.627918,1105023,1105023,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
216,C&L01,Midlothian,2010-11,4.535092,4.535092,3996.571372,3996.571372,882358,882358,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
218,C&L01,Midlothian,2012-13,4.001924,4.001924,3789.070335,4000.000000,946814,946814,3.734560,...,192795.1341,51624697,51624697,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
228,C&L01,Moray,2010-11,2.563313,2.563313,2313.155864,2313.155864,900956,900956,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
240,C&L01,North Ayrshire,2010-11,4.941771,4.941771,5219.081024,5219.081024,1056094,1056094,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
252,C&L01,North Lanarkshire,2010-11,4.917124,4.917124,14829.091370,14829.091370,3016037,3016037,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
264,C&L01,Orkney Islands,2010-11,4.374884,4.374884,1478.842321,1478.842321,337980,337980,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
272,C&L01,Orkney Islands,2018-19,1.164118,1.164118,533.645300,533.645300,458413,458413,2.816481,...,153571.2585,54526069,55526069,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
276,C&L01,Perth & Kinross,2010-11,5.065007,5.065007,5630.692137,5630.692137,1110912,1110912,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
288,C&L01,Renfrewshire,2010-11,2.772814,2.772814,4494.448287,4494.448287,1620261,1620261,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
300,C&L01,Scottish Borders,2010-11,3.894263,3.894263,2859.095154,2859.095154,734048,734048,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
304,C&L01,Scottish Borders,2014-15,3.510090,3.510090,2821.283871,2821.283871,803766,803766,3.408087,...,179623.6567,52705262,52705262,3.403019,3.500000,3508.777729,3508.777729,993567.375,993567.375,Rural
312,C&L01,Shetland Islands,2010-11,1.084478,1.084478,643.296410,643.296410,594858,594858,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
317,C&L01,Shetland Islands,2015-16,1.353606,1.353606,686.970109,686.970109,507509,507509,3.336123,...,177096.5505,53084305,53084305,3.280510,3.280510,3359.409567,3400.000000,1012156.625,1012156.625,Rural
324,C&L01,South Ayrshire,2010-11,6.506870,6.506870,4896.200451,4896.200451,752829,752829,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
332,C&L01,South Ayrshire,2018-19,3.322947,3.322947,3008.897034,3008.897034,905493,905493,2.816481,...,153571.2585,54526069,54526069,2.577170,2.577170,3536.747701,3536.747701,1417414.625,1417414.625,2
336,C&L01,South Lanarkshire,2010-11,4.633680,4.633680,13065.571910,13065.571910,2820195,2820195,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
348,C&L01,Stirling,2010-11,2.933021,2.933021,2799.941461,2799.941461,954067,954067,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
355,C&L01,Stirling,2017-18,2.143167,2.143167,2556.535777,2556.535777,1192884,1292884,2.987480,...,161301.3605,53992733,53992733,2.822089,2.822089,4004.479165,4004.479165,1449852.250,1449852.250,2
360,C&L01,West Dunbartonshire,2010-11,5.545628,5.545628,4453.780123,4453.780123,803853,803853,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
372,C&L01,West Lothian,2010-11,4.498121,4.498121,8455.280970,8455.280970,1879323,1879323,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
382,C&L01,West Lothian,2020-21,22.000649,22.000649,4619.323346,4619.323346,209962,209962,41.360023,...,188666.6714,4561548,4561548,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3

In [ ]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both'] 
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [ ]:
df1 = diff_df
df2 = new_df

out_diff = dataframe_difference(df1, df2)
out_diff

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup,_merge
0,C&L01,Aberdeen City,2010-11,0.406679,785.018799,1922292,4.374884,198956.0517,45459818,4.285538,10653.672510,2200418.875,Urban,left_only
1,C&L01,Aberdeen City,2011-12,0.922524,1886.603428,2045051,3.916959,188806.0265,48202343,4.175469,10198.311630,2355970.750,Urban,left_only
2,C&L01,Aberdeen City,2012-13,4.335545,9381.043169,2163756,3.734560,192795.1341,51624697,4.353732,11272.603250,2601296.500,Urban,left_only
4,C&L01,Aberdeen City,2014-15,3.476122,8645.573117,2487138,3.408087,179623.6567,52705262,4.064669,10315.283210,2672126.125,Urban,left_only
6,C&L01,Aberdeen City,2016-17,3.764976,9022.588442,2396458,3.244026,175314.3718,54042338,3.684838,9674.825435,2702731.625,Urban,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,C&L01,West Dunbartonshire,2010-11,5.545628,4453.780123,803853,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
432,C&L01,West Dunbartonshire,2021-22,5.499331,3447.186068,626835,6.433923,170577.7577,26512151,6.811566,10617.457990,1355678.250,Urban,right_only
433,C&L01,West Lothian,2010-11,4.498121,8455.280970,1879323,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
434,C&L01,West Lothian,2020-21,22.000649,4619.323346,209962,40.000000,188666.6714,4561548,56.111328,4281.674517,119839.625,3,right_only
435,C&L01,West Lothian,2021-22,2.075107,2983.564522,1437783,6.433923,170577.7577,26512151,7.004360,3544.731442,708714.500,3,right_only

In [ ]:
import numpy as np
rows=out_diff.loc[(out_diff['_merge'] == 'right_only')]
rows

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup,_merge
377,C&L01,Aberdeen City,2010-11,0.406679,785.018799,1922292,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
378,C&L01,Aberdeen City,2011-12,0.922524,1886.603428,2045051,3.916959,188806.0265,48202343,4.250000,10198.311630,2355970.750,Urban,right_only
379,C&L01,Aberdeen City,2012-13,4.335545,9381.043169,2163756,3.734560,192795.1341,51624697,4.353732,11272.603250,2612960.500,Urban,right_only
380,C&L01,Aberdeen City,2014-15,3.476122,8600.320000,2487138,3.408087,179623.6567,52705262,4.064669,10315.283210,2672126.125,Urban,right_only
381,C&L01,Aberdeen City,2016-17,3.764976,9022.588442,2400458,3.244026,175314.3718,54042338,3.684838,9674.825435,2702731.625,Urban,right_only
382,C&L01,Aberdeen City,2021-22,4.999658,7172.460000,1434590,6.433923,170577.7577,26512151,6.811566,10617.457990,1355678.250,Urban,right_only
383,C&L01,Aberdeenshire,2010-11,5.520981,6951.791277,1260286,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
384,C&L01,Aberdeenshire,2021-22,5.968627,7080.220429,1186235,6.433923,170577.7577,26512151,5.430648,3186.398948,585801.000,Rural,right_only
385,C&L01,Angus,2010-11,2.415429,3788.301079,1568948,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
386,C&L01,Angus,2012-13,2.121647,2827.522335,1332704,3.800000,192795.1341,51624697,3.362488,4626.408468,1456944.250,3,right_only
387,C&L01,Angus,2021-22,6.279066,3551.101242,565544,6.433923,170577.7577,26512151,7.004360,3544.731442,708714.500,3,right_only
388,C&L01,Argyll & Bute,2010-11,2.982316,1959.466075,656840,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
389,C&L01,Argyll & Bute,2020-21,19.680022,1513.775147,80000,41.360023,188666.6714,4561548,23.984158,3339.028773,144847.375,Rural,right_only
390,C&L01,Argyll & Bute,2021-22,5.823446,1594.698251,273840,6.433923,170577.7577,26512151,5.430648,3186.398948,585801.000,Rural,right_only
391,C&L01,Clackmannanshire,2010-11,3.697085,2019.852137,545939,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
392,C&L01,Clackmannanshire,2020-21,18.000000,790.241941,44319,41.360023,188666.6714,4561548,56.111328,4281.674517,119839.625,3,right_only
393,C&L01,Dumfries & Galloway,2010-11,5.126625,6636.304915,1293585,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
394,C&L01,Dundee City,2010-11,1.922484,2801.173830,1460938,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
395,C&L01,Dundee City,2012-13,3.068683,4492.380815,1463947,3.734560,192795.1341,52000000,4.353732,11272.603250,2601296.500,Urban,right_only
396,C&L01,East Ayrshire,2010-11,2.598255,3094.477557,1190983,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
397,C&L01,East Dunbartonshire,2010-11,3.265759,3227.573365,987719,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
398,C&L01,East Dunbartonshire,2011-12,3.729607,3691.866811,989884,3.916959,188806.0265,50000000,4.175469,10198.311630,2500000.000,Urban,right_only
399,C&L01,East Lothian,2010-11,6.297369,5831.568219,926802,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
400,C&L01,East Renfrewshire,2010-11,6.186456,4484.589338,724197,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
401,C&L01,East Renfrewshire,2011-12,4.628932,3333.727808,720196,3.916959,200000.0000,48202343,3.337976,4860.219433,1415648.375,3,right_only
402,C&L01,Edinburgh City,2010-11,2.945345,11530.040630,3912923,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
403,C&L01,Edinburgh City,2014-15,2.905323,10749.172060,3699830,3.408087,179623.6567,52705262,4.000000,10315.283210,2672126.125,Urban,right_only
404,C&L01,Eilean Siar,2010-11,2.600283,836.778280,321497,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
405,C&L01,Eilean Siar,2018-19,4.000000,986.435251,280371,2.816481,153571.2585,54526069,2.534323,2733.854090,1100968.875,Rural,right_only
406,C&L01,Falkirk,2010-11,6.100191,5742.837680,941279,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
407,C&L01,Fife,2010-11,4.658328,11343.952970,2432587,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
408,C&L01,Glasgow City,2010-11,9.181096,41859.864260,4558310,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
409,C&L01,Glasgow City,2014-15,5.312010,31728.804790,5973048,3.408087,180000.0000,52705262,4.064669,10315.283210,2672126.125,Urban,right_only
410,C&L01,Highland,2010-11,4.103765,8961.784465,2185899,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
411,C&L01,Inverclyde,2010-11,1.774601,1965.627918,1105023,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
412,C&L01,Midlothian,2010-11,4.535092,3996.571372,882358,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
413,C&L01,Midlothian,2012-13,4.001924,4000.000000,946814,3.734560,192795.1341,51624697,3.362488,4626.408468,1456944.250,3,right_only
414,C&L01,Moray,2010-11,2.563313,2313.155864,900956,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
415,C&L01,North Ayrshire,2010-11,4.941771,5219.081024,1056094,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
416,C&L01,North Lanarkshire,2010-11,4.917124,14829.091370,3016037,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
417,C&L01,Orkney Islands,2010-11,4.374884,1478.842321,337980,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
418,C&L01,Orkney Islands,2018-19,1.164118,533.645300,458413,2.816481,153571.2585,55526069,2.534323,2733.854090,1100968.875,Rural,right_only
419,C&L01,Perth & Kinross,2010-11,5.065007,5630.692137,1110912,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
420,C&L01,Renfrewshire,2010-11,2.772814,4494.448287,1620261,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
421,C&L01,Scottish Borders,2010-11,3.894263,2859.095154,734048,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
422,C&L01,Scottish Borders,2014-15,3.510090,2821.283871,803766,3.408087,179623.6567,52705262,3.500000,3508.777729,993567.375,Rural,right_only
423,C&L01,Shetland Islands,2010-11,1.084478,643.296410,594858,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural,right_only
424,C&L01,Shetland Islands,2015-16,1.353606,686.970109,507509,3.336123,177096.5505,53084305,3.280510,3400.000000,1012156.625,Rural,right_only
425,C&L01,South Ayrshire,2010-11,6.506870,4896.200451,752829,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
426,C&L01,South Ayrshire,2018-19,3.322947,3008.897034,905493,3.200000,153571.2585,54526069,2.577170,3536.747701,1417414.625,2,right_only
427,C&L01,South Lanarkshire,2010-11,4.633680,13065.571910,2820195,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
428,C&L01,Stirling,2010-11,2.933021,2799.941461,954067,4.374884,198956.0517,45458000,4.445492,5141.133710,1165653.750,2,right_only
429,C&L01,Stirling,2017-18,2.143167,2556.535777,1292884,2.987480,161301.3605,53992733,2.822089,4004.479165,1449852.250,2,right_only
430,C&L01,Stirling,2021-22,14.557450,3881.831268,266655,6.433923,170577.7577,26512151,7.191427,3973.631332,663825.125,2,right_only
431,C&L01,West Dunbartonshire,2010-11,5.545628,4453.780123,803853,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban,right_only
432,C&L01,West Dunbartonshire,2021-22,5.499331,3447.186068,626835,6.433923,170577.7577,26512151,6.811566,10617.457990,1355678.250,Urban,right_only
433,C&L01,West Lothian,2010-11,4.498121,8455.280970,1879323,4.374884,198956.0517,45458000,3.814160,5283.780376,1393280.500,3,right_only
434,C&L01,West Lothian,2020-21,22.000649,4619.323346,209962,40.000000,188666.6714,4561548,56.111328,4281.674517,119839.625,3,right_only
435,C&L01,West Lothian,2021-22,2.075107,2983.564522,1437783,6.433923,170577.7577,26512151,7.004360,3544.731442,708714.500,3,right_only

In [ ]:
out_same = dataframe_difference(df1, df2, 'both')
out_same

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup,_merge
3,C&L01,Aberdeen City,2013-14,4.044078,8988.323761,2222588,3.710667,197855.9712,53320837,4.355361,11913.659010,2660076.250,Urban,both
5,C&L01,Aberdeen City,2015-16,3.576912,9118.070813,2549135,3.336123,177096.5505,53084305,3.959840,10284.548340,2631837.625,Urban,both
7,C&L01,Aberdeen City,2017-18,3.515156,8767.620763,2494247,2.987480,161301.3605,53992733,3.495988,9382.574231,2680088.000,Urban,both
8,C&L01,Aberdeen City,2018-19,3.837416,8554.495867,2229239,2.816481,153571.2585,54526069,3.264454,9077.495213,2702450.375,Urban,both
9,C&L01,Aberdeen City,2019-20,3.636288,4163.802921,1145072,2.885778,150191.5886,52045545,3.254459,8671.587619,2508488.875,Urban,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,C&L01,West Lothian,2015-16,3.314385,7842.432474,2366170,3.336123,177096.5505,53084305,2.857000,4274.988698,1557697.000,3,both
372,C&L01,West Lothian,2016-17,3.280894,8103.558987,2469929,3.244026,175314.3718,54042338,2.916162,4533.235770,1608040.375,3,both
373,C&L01,West Lothian,2017-18,1.843244,4510.757880,2447198,2.987480,161301.3605,53992733,2.807878,4044.321994,1546902.375,3,both
374,C&L01,West Lothian,2018-19,2.394430,6097.571345,2546572,2.816481,153571.2585,54526069,2.461670,3848.310310,1594924.750,3,both
375,C&L01,West Lothian,2019-20,2.007365,5049.269872,2515378,2.885778,150191.5886,52045545,2.611569,3730.029529,1497042.250,3,both

In [ ]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
merged = temp.merge(diff_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'])
new_year = np.where(merged['Year'].isnull())[0]
new_year

array([ 11,  23,  35,  47, 359, 371, 383])

In [ ]:
#new year added data
new_Data = new_df.loc[new_year]
new_Data

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup
11,C&L01,Aberdeen City,2021-22,4.999658,7172.460000,1434590,6.433923,170577.7577,26512151,6.811566,10617.457990,1355678.250,Urban
23,C&L01,Aberdeenshire,2021-22,5.968627,7080.220429,1186235,6.433923,170577.7577,26512151,5.430648,3186.398948,585801.000,Rural
35,C&L01,Angus,2021-22,6.279066,3551.101242,565544,6.433923,170577.7577,26512151,7.004360,3544.731442,708714.500,3
47,C&L01,Argyll & Bute,2021-22,5.823446,1594.698251,273840,6.433923,170577.7577,26512151,5.430648,3186.398948,585801.000,Rural
359,C&L01,Stirling,2021-22,14.557450,3881.831268,266655,6.433923,170577.7577,26512151,7.191427,3973.631332,663825.125,2
371,C&L01,West Dunbartonshire,2021-22,5.499331,3447.186068,626835,6.433923,170577.7577,26512151,6.811566,10617.457990,1355678.250,Urban
383,C&L01,West Lothian,2021-22,2.075107,2983.564522,1437783,6.433923,170577.7577,26512151,7.004360,3544.731442,708714.500,3

In [ ]:
#make df with only changes
new_test= new_df.drop(new_df.index[new_year], inplace=False).reset_index(drop=True)
new_test.head(15)

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,785.018799,1922292,4.374884,198956.0517,45458000,4.285538,10653.672510,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,1886.603428,2045051,3.916959,188806.0265,48202343,4.250000,10198.311630,2355970.750,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,9381.043169,2163756,3.734560,192795.1341,51624697,4.353732,11272.603250,2612960.500,Urban
3,C&L01,Aberdeen City,2013-14,4.044078,8988.323761,2222588,3.710667,197855.9712,53320837,4.355361,11913.659010,2660076.250,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,8600.320000,2487138,3.408087,179623.6567,52705262,4.064669,10315.283210,2672126.125,Urban
5,C&L01,Aberdeen City,2015-16,3.576912,9118.070813,2549135,3.336123,177096.5505,53084305,3.959840,10284.548340,2631837.625,Urban
6,C&L01,Aberdeen City,2016-17,3.764976,9022.588442,2400458,3.244026,175314.3718,54042338,3.684838,9674.825435,2702731.625,Urban
7,C&L01,Aberdeen City,2017-18,3.515156,8767.620763,2494247,2.987480,161301.3605,53992733,3.495988,9382.574231,2680088.000,Urban
8,C&L01,Aberdeen City,2018-19,3.837416,8554.495867,2229239,2.816481,153571.2585,54526069,3.264454,9077.495213,2702450.375,Urban
9,C&L01,Aberdeen City,2019-20,3.636288,4163.802921,1145072,2.885778,150191.5886,52045545,3.254459,8671.587619,2508488.875,Urban
10,C&L01,Aberdeen City,2020-21,28.408215,7216.858869,254040,41.360023,188666.6714,4561548,68.690228,11504.306260,200665.375,Urban
11,C&L01,Aberdeenshire,2010-11,5.520981,6951.791277,1260286,4.374884,198956.0517,45458000,3.710950,3790.919862,923124.125,Rural
12,C&L01,Aberdeenshire,2011-12,3.501223,6646.817097,1898433,3.916959,188806.0265,48202343,3.689641,3901.135322,1036476.000,Rural
13,C&L01,Aberdeenshire,2012-13,3.712267,7498.408348,2019904,3.734560,192795.1341,51624697,3.297381,3775.533691,1065939.000,Rural
14,C&L01,Aberdeenshire,2013-14,3.700062,7501.515870,2027402,3.710667,197855.9712,53320837,3.179201,3436.061899,1040247.500,Rural

In [ ]:
import numpy as np
#compare the old df to find the changes
comparison_values = diff_df.values == new_test.values
rows,cols=np.where(comparison_values==False)
rows

array([  0,   1,   2,   4,   6,  11,  22,  24,  33,  43,  44,  54,  56,
        68,  70,  80,  92,  93,  93, 104, 116, 117, 128, 132, 140, 148,
       152, 164, 176, 180, 188, 200, 212, 214, 224, 236, 248, 260, 268,
       272, 284, 296, 300, 308, 313, 320, 328, 332, 344, 351, 355, 366,
       376])

In [ ]:
change_df = pd.DataFrame()
change_df = diff_df.loc[rows]
AddNew_df = new_test.loc[rows]
change_df.insert(loc = 4, column = "New_LA_Indicator", value = AddNew_df["LA_IndicatorReal"].values)
change_df.insert(loc = 6, column = "New_LA_Numerator", value = AddNew_df["LA_Numerator_real"].values)
change_df.insert(loc = 8, column ="New_LA_Den", value = AddNew_df["LA_Den_Real"].values)
change_df.insert(loc = 10, column = "New_Scotland_Indicator", value = AddNew_df["Scotland_Indicator_Real"].values)
change_df.insert(loc = 12, column = "New_Scotland_Num", value = AddNew_df["Scotland_Num_Real"].values)
change_df.insert(loc = 14, column ="New_Scotland_Den", value = AddNew_df["Scotland_Den_Real"].values)
change_df.insert(loc = 16, column ="New_FG_Avg_Indicator", value = AddNew_df["FG_Avg_Indicator_Real"].values)
change_df.insert(loc = 18, column ="New_FG_Avg_Num", value = AddNew_df["FG_Avg_Num_Real"].values)
change_df.insert(loc = 20, column ="New_FG_Avg_Den", value = AddNew_df["FG_Avg_Den_Real"].values)
change_df

,Code,LocalAuthority,Year,LA_IndicatorReal,New_LA_Indicator,LA_Numerator_real,New_LA_Numerator,LA_Den_Real,New_LA_Den,Scotland_Indicator_Real,...,New_Scotland_Num,Scotland_Den_Real,New_Scotland_Den,FG_Avg_Indicator_Real,New_FG_Avg_Indicator,FG_Avg_Num_Real,New_FG_Avg_Num,FG_Avg_Den_Real,New_FG_Avg_Den,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,0.406679,785.018799,785.018799,1922292,1922292,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,0.922524,1886.603428,1886.603428,2045051,2045051,3.916959,...,188806.0265,48202343,48202343,4.175469,4.250000,10198.311630,10198.311630,2355970.750,2355970.750,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,4.335545,9381.043169,9381.043169,2163756,2163756,3.734560,...,192795.1341,51624697,51624697,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2612960.500,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,3.476122,8645.573117,8600.320000,2487138,2487138,3.408087,...,179623.6567,52705262,52705262,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
6,C&L01,Aberdeen City,2016-17,3.764976,3.764976,9022.588442,9022.588442,2396458,2400458,3.244026,...,175314.3718,54042338,54042338,3.684838,3.684838,9674.825435,9674.825435,2702731.625,2702731.625,Urban
11,C&L01,Aberdeenshire,2010-11,5.520981,5.520981,6951.791277,6951.791277,1260286,1260286,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
22,C&L01,Angus,2010-11,2.415429,2.415429,3788.301079,3788.301079,1568948,1568948,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
24,C&L01,Angus,2012-13,2.121647,2.121647,2827.522335,2827.522335,1332704,1332704,3.734560,...,192795.1341,51624697,51624697,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
33,C&L01,Argyll & Bute,2010-11,2.982316,2.982316,1959.466075,1959.466075,656840,656840,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
43,C&L01,Argyll & Bute,2020-21,19.680022,19.680022,1513.775147,1513.775147,76919,80000,41.360023,...,188666.6714,4561548,4561548,23.984158,23.984158,3339.028773,3339.028773,144847.375,144847.375,Rural
44,C&L01,Clackmannanshire,2010-11,3.697085,3.697085,2019.852137,2019.852137,545939,545939,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
54,C&L01,Clackmannanshire,2020-21,17.830682,18.000000,790.241941,790.241941,44319,44319,41.360023,...,188666.6714,4561548,4561548,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3
56,C&L01,Dumfries & Galloway,2010-11,5.126625,5.126625,6636.304915,6636.304915,1293585,1293585,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
68,C&L01,Dundee City,2010-11,1.922484,1.922484,2801.173830,2801.173830,1460938,1460938,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
70,C&L01,Dundee City,2012-13,3.068683,3.068683,4492.380815,4492.380815,1463947,1463947,3.734560,...,192795.1341,51624697,52000000,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2601296.500,Urban
80,C&L01,East Ayrshire,2010-11,2.598255,2.598255,3094.477557,3094.477557,1190983,1190983,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
92,C&L01,East Dunbartonshire,2010-11,3.265759,3.265759,3227.573365,3227.573365,987719,987719,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
93,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884,3.916959,...,188806.0265,48202343,50000000,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
93,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884,3.916959,...,188806.0265,48202343,50000000,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
104,C&L01,East Lothian,2010-11,6.297369,6.297369,5831.568219,5831.568219,926802,926802,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
116,C&L01,East Renfrewshire,2010-11,6.186456,6.186456,4484.589338,4484.589338,724197,724197,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
117,C&L01,East Renfrewshire,2011-12,4.628932,4.628932,3333.727808,3333.727808,720196,720196,3.916959,...,200000.0000,48202343,48202343,3.337976,3.337976,4860.219433,4860.219433,1415648.375,1415648.375,3
128,C&L01,Edinburgh City,2010-11,2.945345,2.945345,11530.040630,11530.040630,3912923,3912923,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
132,C&L01,Edinburgh City,2014-15,2.905323,2.905323,10749.172060,10749.172060,3699830,3699830,3.408087,...,179623.6567,52705262,52705262,4.064669,4.000000,10315.283210,10315.283210,2672126.125,2672126.125,Urban
140,C&L01,Eilean Siar,2010-11,2.600283,2.600283,836.778280,836.778280,321497,321497,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
148,C&L01,Eilean Siar,2018-19,3.518330,4.000000,986.435251,986.435251,280371,280371,2.816481,...,153571.2585,54526069,54526069,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
152,C&L01,Falkirk,2010-11,6.100191,6.100191,5742.837680,5742.837680,941279,941279,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
164,C&L01,Fife,2010-11,4.658328,4.658328,11343.952970,11343.952970,2432587,2432587,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
176,C&L01,Glasgow City,2010-11,9.181096,9.181096,41859.864260,41859.864260,4558310,4558310,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
180,C&L01,Glasgow City,2014-15,5.312010,5.312010,31728.804790,31728.804790,5973048,5973048,3.408087,...,180000.0000,52705262,52705262,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
188,C&L01,Highland,2010-11,4.103765,4.103765,8961.784465,8961.784465,2185899,2185899,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
200,C&L01,Inverclyde,2010-11,1.774601,1.774601,1965.627918,1965.627918,1105023,1105023,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
212,C&L01,Midlothian,2010-11,4.535092,4.535092,3996.571372,3996.571372,882358,882358,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
214,C&L01,Midlothian,2012-13,4.001924,4.001924,3789.070335,4000.000000,946814,946814,3.734560,...,192795.1341,51624697,51624697,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
224,C&L01,Moray,2010-11,2.563313,2.563313,2313.155864,2313.155864,900956,900956,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
236,C&L01,North Ayrshire,2010-11,4.941771,4.941771,5219.081024,5219.081024,1056094,1056094,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
248,C&L01,North Lanarkshire,2010-11,4.917124,4.917124,14829.091370,14829.091370,3016037,3016037,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
260,C&L01,Orkney Islands,2010-11,4.374884,4.374884,1478.842321,1478.842321,337980,337980,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
268,C&L01,Orkney Islands,2018-19,1.164118,1.164118,533.645300,533.645300,458413,458413,2.816481,...,153571.2585,54526069,55526069,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
272,C&L01,Perth & Kinross,2010-11,5.065007,5.065007,5630.692137,5630.692137,1110912,1110912,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
284,C&L01,Renfrewshire,2010-11,2.772814,2.772814,4494.448287,4494.448287,1620261,1620261,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
296,C&L01,Scottish Borders,2010-11,3.894263,3.894263,2859.095154,2859.095154,734048,734048,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
300,C&L01,Scottish Borders,2014-15,3.510090,3.510090,2821.283871,2821.283871,803766,803766,3.408087,...,179623.6567,52705262,52705262,3.403019,3.500000,3508.777729,3508.777729,993567.375,993567.375,Rural
308,C&L01,Shetland Islands,2010-11,1.084478,1.084478,643.296410,643.296410,594858,594858,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
313,C&L01,Shetland Islands,2015-16,1.353606,1.353606,686.970109,686.970109,507509,507509,3.336123,...,177096.5505,53084305,53084305,3.280510,3.280510,3359.409567,3400.000000,1012156.625,1012156.625,Rural
320,C&L01,South Ayrshire,2010-11,6.506870,6.506870,4896.200451,4896.200451,752829,752829,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
328,C&L01,South Ayrshire,2018-19,3.322947,3.322947,3008.897034,3008.897034,905493,905493,2.816481,...,153571.2585,54526069,54526069,2.577170,2.577170,3536.747701,3536.747701,1417414.625,1417414.625,2
332,C&L01,South Lanarkshire,2010-11,4.633680,4.633680,13065.571910,13065.571910,2820195,2820195,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
344,C&L01,Stirling,2010-11,2.933021,2.933021,2799.941461,2799.941461,954067,954067,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
351,C&L01,Stirling,2017-18,2.143167,2.143167,2556.535777,2556.535777,1192884,1292884,2.987480,...,161301.3605,53992733,53992733,2.822089,2.822089,4004.479165,4004.479165,1449852.250,1449852.250,2
355,C&L01,West Dunbartonshire,2010-11,5.545628,5.545628,4453.780123,4453.780123,803853,803853,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
366,C&L01,West Lothian,2010-11,4.498121,4.498121,8455.280970,8455.280970,1879323,1879323,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
376,C&L01,West Lothian,2020-21,22.000649,22.000649,4619.323346,4619.323346,209962,209962,41.360023,...,188666.6714,4561548,4561548,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3

In [ ]:
#Add all changes including new data for the new year

All_changes = pd.concat([change_df, new_Data], axis=0).reset_index()
All_changes

,index,Code,LocalAuthority,Year,LA_IndicatorReal,New_LA_Indicator,LA_Numerator_real,New_LA_Numerator,LA_Den_Real,New_LA_Den,...,New_Scotland_Num,Scotland_Den_Real,New_Scotland_Den,FG_Avg_Indicator_Real,New_FG_Avg_Indicator,FG_Avg_Num_Real,New_FG_Avg_Num,FG_Avg_Den_Real,New_FG_Avg_Den,FamilyGroup
0,0,C&L01,Aberdeen City,2010-11,0.406679,0.406679,785.018799,785.018799,1922292,1922292.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
1,1,C&L01,Aberdeen City,2011-12,0.922524,0.922524,1886.603428,1886.603428,2045051,2045051.0,...,188806.0265,48202343,48202343.0,4.175469,4.250000,10198.311630,10198.311630,2355970.750,2355970.750,Urban
2,2,C&L01,Aberdeen City,2012-13,4.335545,4.335545,9381.043169,9381.043169,2163756,2163756.0,...,192795.1341,51624697,51624697.0,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2612960.500,Urban
3,4,C&L01,Aberdeen City,2014-15,3.476122,3.476122,8645.573117,8600.320000,2487138,2487138.0,...,179623.6567,52705262,52705262.0,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
4,6,C&L01,Aberdeen City,2016-17,3.764976,3.764976,9022.588442,9022.588442,2396458,2400458.0,...,175314.3718,54042338,54042338.0,3.684838,3.684838,9674.825435,9674.825435,2702731.625,2702731.625,Urban
5,11,C&L01,Aberdeenshire,2010-11,5.520981,5.520981,6951.791277,6951.791277,1260286,1260286.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
6,22,C&L01,Angus,2010-11,2.415429,2.415429,3788.301079,3788.301079,1568948,1568948.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
7,24,C&L01,Angus,2012-13,2.121647,2.121647,2827.522335,2827.522335,1332704,1332704.0,...,192795.1341,51624697,51624697.0,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
8,33,C&L01,Argyll & Bute,2010-11,2.982316,2.982316,1959.466075,1959.466075,656840,656840.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
9,43,C&L01,Argyll & Bute,2020-21,19.680022,19.680022,1513.775147,1513.775147,76919,80000.0,...,188666.6714,4561548,4561548.0,23.984158,23.984158,3339.028773,3339.028773,144847.375,144847.375,Rural
10,44,C&L01,Clackmannanshire,2010-11,3.697085,3.697085,2019.852137,2019.852137,545939,545939.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
11,54,C&L01,Clackmannanshire,2020-21,17.830682,18.000000,790.241941,790.241941,44319,44319.0,...,188666.6714,4561548,4561548.0,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3
12,56,C&L01,Dumfries & Galloway,2010-11,5.126625,5.126625,6636.304915,6636.304915,1293585,1293585.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
13,68,C&L01,Dundee City,2010-11,1.922484,1.922484,2801.173830,2801.173830,1460938,1460938.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
14,70,C&L01,Dundee City,2012-13,3.068683,3.068683,4492.380815,4492.380815,1463947,1463947.0,...,192795.1341,51624697,52000000.0,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2601296.500,Urban
15,80,C&L01,East Ayrshire,2010-11,2.598255,2.598255,3094.477557,3094.477557,1190983,1190983.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
16,92,C&L01,East Dunbartonshire,2010-11,3.265759,3.265759,3227.573365,3227.573365,987719,987719.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
17,93,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884.0,...,188806.0265,48202343,50000000.0,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
18,93,C&L01,East Dunbartonshire,2011-12,3.729607,3.729607,3691.866811,3691.866811,989884,989884.0,...,188806.0265,48202343,50000000.0,4.175469,4.175469,10198.311630,10198.311630,2355970.750,2500000.000,Urban
19,104,C&L01,East Lothian,2010-11,6.297369,6.297369,5831.568219,5831.568219,926802,926802.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
20,116,C&L01,East Renfrewshire,2010-11,6.186456,6.186456,4484.589338,4484.589338,724197,724197.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
21,117,C&L01,East Renfrewshire,2011-12,4.628932,4.628932,3333.727808,3333.727808,720196,720196.0,...,200000.0000,48202343,48202343.0,3.337976,3.337976,4860.219433,4860.219433,1415648.375,1415648.375,3
22,128,C&L01,Edinburgh City,2010-11,2.945345,2.945345,11530.040630,11530.040630,3912923,3912923.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
23,132,C&L01,Edinburgh City,2014-15,2.905323,2.905323,10749.172060,10749.172060,3699830,3699830.0,...,179623.6567,52705262,52705262.0,4.064669,4.000000,10315.283210,10315.283210,2672126.125,2672126.125,Urban
24,140,C&L01,Eilean Siar,2010-11,2.600283,2.600283,836.778280,836.778280,321497,321497.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
25,148,C&L01,Eilean Siar,2018-19,3.518330,4.000000,986.435251,986.435251,280371,280371.0,...,153571.2585,54526069,54526069.0,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
26,152,C&L01,Falkirk,2010-11,6.100191,6.100191,5742.837680,5742.837680,941279,941279.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
27,164,C&L01,Fife,2010-11,4.658328,4.658328,11343.952970,11343.952970,2432587,2432587.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
28,176,C&L01,Glasgow City,2010-11,9.181096,9.181096,41859.864260,41859.864260,4558310,4558310.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
29,180,C&L01,Glasgow City,2014-15,5.312010,5.312010,31728.804790,31728.804790,5973048,5973048.0,...,180000.0000,52705262,52705262.0,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
30,188,C&L01,Highland,2010-11,4.103765,4.103765,8961.784465,8961.784465,2185899,2185899.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
31,200,C&L01,Inverclyde,2010-11,1.774601,1.774601,1965.627918,1965.627918,1105023,1105023.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
32,212,C&L01,Midlothian,2010-11,4.535092,4.535092,3996.571372,3996.571372,882358,882358.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
33,214,C&L01,Midlothian,2012-13,4.001924,4.001924,3789.070335,4000.000000,946814,946814.0,...,192795.1341,51624697,51624697.0,3.362488,3.362488,4626.408468,4626.408468,1456944.250,1456944.250,3
34,224,C&L01,Moray,2010-11,2.563313,2.563313,2313.155864,2313.155864,900956,900956.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
35,236,C&L01,North Ayrshire,2010-11,4.941771,4.941771,5219.081024,5219.081024,1056094,1056094.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
36,248,C&L01,North Lanarkshire,2010-11,4.917124,4.917124,14829.091370,14829.091370,3016037,3016037.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
37,260,C&L01,Orkney Islands,2010-11,4.374884,4.374884,1478.842321,1478.842321,337980,337980.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
38,268,C&L01,Orkney Islands,2018-19,1.164118,1.164118,533.645300,533.645300,458413,458413.0,...,153571.2585,54526069,55526069.0,2.534323,2.534323,2733.854090,2733.854090,1100968.875,1100968.875,Rural
39,272,C&L01,Perth & Kinross,2010-11,5.065007,5.065007,5630.692137,5630.692137,1110912,1110912.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
40,284,C&L01,Renfrewshire,2010-11,2.772814,2.772814,4494.448287,4494.448287,1620261,1620261.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
41,296,C&L01,Scottish Borders,2010-11,3.894263,3.894263,2859.095154,2859.095154,734048,734048.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
42,300,C&L01,Scottish Borders,2014-15,3.510090,3.510090,2821.283871,2821.283871,803766,803766.0,...,179623.6567,52705262,52705262.0,3.403019,3.500000,3508.777729,3508.777729,993567.375,993567.375,Rural
43,308,C&L01,Shetland Islands,2010-11,1.084478,1.084478,643.296410,643.296410,594858,594858.0,...,198956.0517,45459818,45458000.0,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
44,313,C&L01,Shetland Islands,2015-16,1.353606,1.353606,686.970109,686.970109,507509,507509.0,...,177096.5505,53084305,53084305.0,3.280510,3.280510,3359.409567,3400.000000,1012156.625,1012156.625,Rural
45,320,C&L01,South Ayrshire,2010-11,6.506870,6.506870,4896.200451,4896.200451,752829,752829.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
46,328,C&L01,South Ayrshire,2018-19,3.322947,3.322947,3008.897034,3008.897034,905493,905493.0,...,153571.2585,54526069,54526069.0,2.577170,2.577170,3536.747701,3536.747701,1417414.625,1417414.625,2
47,332,C&L01,South Lanarkshire,2010-11,4.633680,4.633680,13065.571910,13065.571910,2820195,2820195.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
48,344,C&L01,Stirling,2010-11,2.933021,2.933021,2799.941461,2799.941461,954067,954067.0,...,198956.0517,45459818,45458000.0,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
49,351,C&L01,Stirling,2017-18,2.143167,2.143167,2556.535777,2556.535777,1192884,1292884.0,...,161301.3605,53992733,53992733.0,2.822089,2.822089,4004.479165,4004.479165,1449852.250,1449852.250,2
50,355,C&L01,West Dunbartonshire,2010-11,5.545628,5.545628,4453.780123,4453.780123,803853,803853.0,...,198956.0517,45459818,45458000.0,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
51,366,C&L01,West Lothian,2010-11,4.498121,4.498121,8455.280970,8455.280970,1879323,1879323.0,...,198956.0517,45459818,45458000.0,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
52,376,C&L01,West Lothian,2020-21,22.000649,22.000649,4619.323346,4619.323346,209962,209962.0,...,188666.6714,4561548,4561548.0,56.111328,56.111328,4281.674517,4281.674517,119839.625,119839.625,3
53,11,C&L01,Aberdeen City,2021-22,4.999658,NaN,7172.460000,NaN,1434590,NaN,...,NaN,26512151,NaN,6.811566,NaN,10617.457990,NaN,1355678.250,NaN,Urban
54,23,C&L01,Aberdeenshire,2021-22,5.968627,NaN,7080.220429,NaN,1186235,NaN,...,NaN,26512151,NaN,5.430648,NaN,3186.398948,NaN,585801.000,NaN,Rural
55,35,C&L01,Angus,2021-22,6.279066,NaN,3551.101242,NaN,565544,NaN,...,NaN,26512151,NaN,7.004360,NaN,3544.731442,NaN,708714.500,NaN,3
56,47,C&L01,Argyll & Bute,2021-22,5.823446,NaN,1594.698251,NaN,273840,NaN,...,NaN,26512151,NaN,5.430648,NaN,3186.398948,NaN,585801.000,NaN,Rural
57,359,C&L01,Stirling,2021-22,14.557450,NaN,3881.831268,NaN,266655,NaN,...,NaN,26512151,NaN,7.191427,NaN,3973.631332,NaN,663825.125,NaN,2
58,371,C&L01,West Dunbartonshire,2021-22,5.499331,NaN,3447.186068,NaN,626835,NaN,...,NaN,26512151,NaN,6.811566,NaN,10617.457990,NaN,1355678.250,NaN,Urban
59,383,C&L01,West Lothian,2021-22,2.075107,NaN,2983.564522,NaN,1437783,NaN,...,NaN,26512151,NaN,7.004360,NaN,3544.731442,NaN,708714.500,NaN,3

In [ ]:
# Get Index for Multiple Column Labels/Names
query_cols=['LA_IndicatorReal','New_LA_Indicator', "LA_Numerator_real", "New_LA_Numerator","LA_Den_Real", "New_LA_Den","Scotland_Indicator_Real", "New_Scotland_Indicator", "Scotland_Num_Real","New_Scotland_Num", "Scotland_Den_Real", "New_Scotland_Den","FG_Avg_Indicator_Real","New_FG_Avg_Indicator","FG_Avg_Num_Real","New_FG_Avg_Num","FG_Avg_Den_Real","New_FG_Avg_Den"]
cols_index = [All_changes.columns.get_loc(col) for col in query_cols]
print(cols_index)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [ ]:
def highlight_cell(x):
    return ['background-color: yellow' if x['LA_IndicatorReal']- x['New_LA_Indicator']!=0 else '' for x in x]

All_changes.style.apply(highlight_cell, subset=pd.IndexSlice[All_changes.index, ['New_LA_Indicator']])

TypeError: ignored