<a href="https://colab.research.google.com/github/JaySanthanam/Programming-for-data/blob/main/Projects/Work_in_progress/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

In [246]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

url_new = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/test_new.csv"
new_df = get_data(url_new)
url_old = "https://raw.githubusercontent.com/JaySanthanam/Programming-for-data/main/Datasets/test_old.csv"
old_df = get_data(url_old)

In [247]:
old_df.shape[0]

384

In [248]:
old_df.equals(new_df)

False

In [249]:
comparison_values = old_df.values == new_df.values
print(comparison_values)

[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True False  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]

In [250]:
import numpy as np
rows,cols=np.where(comparison_values==False)

In [251]:
out_df = get_data(url_old)

In [252]:
for item in zip(rows,cols):
    if old_df.iloc[item] != new_df.iloc[item]:
       out_df.iloc[item[0], item[1]] = '{} --> {}'.format(old_df.iloc[item[0], item[1]],new_df.iloc[item[0], item[1]])

In [253]:
out_df.shape[0]

384

In [254]:
out_df = out_df.dropna(how='all', axis=0)
out_df.head(10)

,Code,LocalAuthority,Year,LA_IndicatorReal,LA_Numerator_real,LA_Den_Real,Scotland_Indicator_Real,Scotland_Num_Real,Scotland_Den_Real,FG_Avg_Indicator_Real,FG_Avg_Num_Real,FG_Avg_Den_Real,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,785.018799,1922292,4.374884,198956.0517,45459818 --> 45458000,4.285538,10653.672510,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,1886.603428,2045051,3.916959,188806.0265,48202343,4.175468725 --> 4.25,10198.311630,2355970.75,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,9381.043169,2163756,3.734560,192795.1341,51624697,4.353732,11272.603250,2601296.5 --> 2612960.5,Urban
3,C&L01,Aberdeen City,2013-14,4.044078,8988.323761,2222588,3.710667,197855.9712,53320837,4.355361,11913.659010,2660076.25,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,8645.573117 --> 8600.32,2487138,3.408087,179623.6567,52705262,4.064669,10315.283210,2672126.125,Urban
5,C&L01,Aberdeen City,2015-16,3.576912,9118.070813,2549135,3.336123,177096.5505,53084305,3.95984,10284.548340,2631837.625,Urban
6,C&L01,Aberdeen City,2016-17,3.764976,9022.588442,2396458 --> 2400458,3.244026,175314.3718,54042338,3.684838,9674.825435,2702731.625,Urban
7,C&L01,Aberdeen City,2017-18,3.515156,8767.620763,2494247,2.987480,161301.3605,53992733,3.495988,9382.574231,2680088.0,Urban
8,C&L01,Aberdeen City,2018-19,3.837416,8554.495867,2229239,2.816481,153571.2585,54526069,3.264454,9077.495213,2702450.375,Urban
9,C&L01,Aberdeen City,2019-20,3.636288,4163.802921,1145072,2.885778,150191.5886,52045545,3.254459,8671.587619,2508488.875,Urban

In [255]:
out_df.to_csv(r'C:\Users\santhanam.jayanthi\Desktop\out_df.csv',index=False, header=True)

Let's try the index match

In [256]:
test_df = pd.DataFrame()

In [257]:
test_df = old_df.loc[rows]

In [258]:
test1_df = new_df.loc[rows]

In [259]:
test_df.insert(loc = 4, column = "New_LA_Indicator", value = test1_df["LA_IndicatorReal"].values)
test_df.insert(loc = 6, column = "New_LA_Numerator", value = test1_df["LA_Numerator_real"].values)
test_df.insert(loc = 8, column ="New_LA_Den", value = test1_df["LA_Den_Real"].values)
test_df.insert(loc = 10, column = "New_Scotland_Indicator", value = test1_df["Scotland_Indicator_Real"].values)
test_df.insert(loc = 12, column = "New_Scotland_Num", value = test1_df["Scotland_Num_Real"].values)
test_df.insert(loc = 14, column ="New_Scotland_Den", value = test1_df["Scotland_Den_Real"].values)
test_df.insert(loc = 16, column ="New_FG_Avg_Indicator", value = test1_df["FG_Avg_Indicator_Real"].values)
test_df.insert(loc = 18, column ="New_FG_Avg_Num", value = test1_df["FG_Avg_Num_Real"].values)
test_df.insert(loc = 20, column ="New_FG_Avg_Den", value = test1_df["FG_Avg_Den_Real"].values)

In [260]:
test_df

,Code,LocalAuthority,Year,LA_IndicatorReal,New_LA_Indicator,LA_Numerator_real,New_LA_Numerator,LA_Den_Real,New_LA_Den,Scotland_Indicator_Real,...,New_Scotland_Num,Scotland_Den_Real,New_Scotland_Den,FG_Avg_Indicator_Real,New_FG_Avg_Indicator,FG_Avg_Num_Real,New_FG_Avg_Num,FG_Avg_Den_Real,New_FG_Avg_Den,FamilyGroup
0,C&L01,Aberdeen City,2010-11,0.406679,0.406679,785.018799,785.018799,1922292,1922292,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
1,C&L01,Aberdeen City,2011-12,0.922524,0.922524,1886.603428,1886.603428,2045051,2045051,3.916959,...,188806.0265,48202343,48202343,4.175469,4.250000,10198.311630,10198.311630,2355970.750,2355970.750,Urban
2,C&L01,Aberdeen City,2012-13,4.335545,4.335545,9381.043169,9381.043169,2163756,2163756,3.734560,...,192795.1341,51624697,51624697,4.353732,4.353732,11272.603250,11272.603250,2601296.500,2612960.500,Urban
4,C&L01,Aberdeen City,2014-15,3.476122,3.476122,8645.573117,8600.320000,2487138,2487138,3.408087,...,179623.6567,52705262,52705262,4.064669,4.064669,10315.283210,10315.283210,2672126.125,2672126.125,Urban
6,C&L01,Aberdeen City,2016-17,3.764976,3.764976,9022.588442,9022.588442,2396458,2400458,3.244026,...,175314.3718,54042338,54042338,3.684838,3.684838,9674.825435,9674.825435,2702731.625,2702731.625,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
11,C&L01,Aberdeen City,2021-22,4.797766,4.999658,6882.381924,7172.460000,1434492,1434590,6.433923,...,170577.7577,26512151,26512151,6.811566,6.811566,10617.457990,10617.457990,1355678.250,1355678.250,Urban
12,C&L01,Aberdeenshire,2010-11,5.520981,5.520981,6951.791277,6951.791277,1260286,1260286,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
24,C&L01,Angus,2010-11,2.415429,2.415429,3788.301079,3788.301079,1568948,1568948,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
36,C&L01,Argyll & Bute,2010-11,2.982316,2.982316,1959.466075,1959.466075,656840,656840,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
48,C&L01,Clackmannanshire,2010-11,3.697085,3.697085,2019.852137,2019.852137,545939,545939,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
60,C&L01,Dumfries & Galloway,2010-11,5.126625,5.126625,6636.304915,6636.304915,1293585,1293585,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
72,C&L01,Dundee City,2010-11,1.922484,1.922484,2801.173830,2801.173830,1460938,1460938,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
84,C&L01,East Ayrshire,2010-11,2.598255,2.598255,3094.477557,3094.477557,1190983,1190983,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
96,C&L01,East Dunbartonshire,2010-11,3.265759,3.265759,3227.573365,3227.573365,987719,987719,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
108,C&L01,East Lothian,2010-11,6.297369,6.297369,5831.568219,5831.568219,926802,926802,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
120,C&L01,East Renfrewshire,2010-11,6.186456,6.186456,4484.589338,4484.589338,724197,724197,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
132,C&L01,Edinburgh City,2010-11,2.945345,2.945345,11530.040630,11530.040630,3912923,3912923,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
144,C&L01,Eilean Siar,2010-11,2.600283,2.600283,836.778280,836.778280,321497,321497,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
156,C&L01,Falkirk,2010-11,6.100191,6.100191,5742.837680,5742.837680,941279,941279,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
168,C&L01,Fife,2010-11,4.658328,4.658328,11343.952970,11343.952970,2432587,2432587,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
180,C&L01,Glasgow City,2010-11,9.181096,9.181096,41859.864260,41859.864260,4558310,4558310,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
192,C&L01,Highland,2010-11,4.103765,4.103765,8961.784465,8961.784465,2185899,2185899,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
204,C&L01,Inverclyde,2010-11,1.774601,1.774601,1965.627918,1965.627918,1105023,1105023,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
216,C&L01,Midlothian,2010-11,4.535092,4.535092,3996.571372,3996.571372,882358,882358,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
228,C&L01,Moray,2010-11,2.563313,2.563313,2313.155864,2313.155864,900956,900956,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
240,C&L01,North Ayrshire,2010-11,4.941771,4.941771,5219.081024,5219.081024,1056094,1056094,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
252,C&L01,North Lanarkshire,2010-11,4.917124,4.917124,14829.091370,14829.091370,3016037,3016037,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
264,C&L01,Orkney Islands,2010-11,4.374884,4.374884,1478.842321,1478.842321,337980,337980,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
276,C&L01,Perth & Kinross,2010-11,5.065007,5.065007,5630.692137,5630.692137,1110912,1110912,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
288,C&L01,Renfrewshire,2010-11,2.772814,2.772814,4494.448287,4494.448287,1620261,1620261,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
300,C&L01,Scottish Borders,2010-11,3.894263,3.894263,2859.095154,2859.095154,734048,734048,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
312,C&L01,Shetland Islands,2010-11,1.084478,1.084478,643.296410,643.296410,594858,594858,4.374884,...,198956.0517,45459818,45458000,3.710950,3.710950,3790.919862,3790.919862,923124.125,923124.125,Rural
324,C&L01,South Ayrshire,2010-11,6.506870,6.506870,4896.200451,4896.200451,752829,752829,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
336,C&L01,South Lanarkshire,2010-11,4.633680,4.633680,13065.571910,13065.571910,2820195,2820195,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3
348,C&L01,Stirling,2010-11,2.933021,2.933021,2799.941461,2799.941461,954067,954067,4.374884,...,198956.0517,45459818,45458000,4.445492,4.445492,5141.133710,5141.133710,1165653.750,1165653.750,2
360,C&L01,West Dunbartonshire,2010-11,5.545628,5.545628,4453.780123,4453.780123,803853,803853,4.374884,...,198956.0517,45459818,45458000,4.285538,4.285538,10653.672510,10653.672510,2200418.875,2200418.875,Urban
372,C&L01,West Lothian,2010-11,4.498121,4.498121,8455.280970,8455.280970,1879323,1879323,4.374884,...,198956.0517,45459818,45458000,3.814160,3.814160,5283.780376,5283.780376,1393280.500,1393280.500,3